/run/verbose 0
/run/initialize

/vis/open OGLSQt 2000x3000-0+0

/vis/verbose errors
/vis/viewer/set/autoRefresh false

/vis/viewer/set/style surface
/vis/viewer/set/hiddenEdge false

/vis/viewer/reset
/vis/drawVolume
/vis/geometry/set/visibility World 0 false

/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointThetaPhi 70 250
/vis/viewer/zoom 1.2
/vis/viewer/set/lightsVector 0.75 -0.5 1
/vis/viewer/set/lineSegmentsPerCircle 50

/vis/viewer/set/background 1.0 1.0 1.0 0.0
